### ISSUE TITLE
ndive-design-system 감상후기

### ISSUE THREAD

**Issue by yceffort** [yujeongJeon/ndive-design-system#45]
- apps 와 examples 는 별도로 분리하신 이유가 있나요? examples에 있는 `shopping-web`이 `apps`안에 들어가도 될거같아서 여쭙습니다.
- (딴소리) 저랑 코드 스타일이 좀 달라서 다른 사람인게 확느껴지네요 ㅋㅋ 타입에 `T`prefix 라던가 파일명 중간에 `.types.ts`라던가..
- `vite.config.mts` 들 그냥 `ts`로 바꾸셔도 무방할 것 같습니다.

https://github.com/yujeongJeon/ndive-design-system/blob/043f8e68c4e0f436f70123cb0214b727cc6113f9/packages/design-components/src/components/icons/IconApple.tsx#L22

- 이렇게 고정값으로 박혀있는 `id`나중에 문제되지는 않겠죠?

> 오랜시간 봤지만,, 흠잡을 곳이 없는 프로덕트였습니다.. 갓 유 정

**Comment by yujeongJeon** [comment]
> apps 와 examples 는 별도로 분리하신 이유가 있나요? examples에 있는 shopping-web이 apps안에 들어가도 될거같아서 여쭙습니다.

- 아하 사실 오픈소스 보니까 사용자 입장에서 참고해야 할 경로는 1-depth로 빼두는게 사용자 입장에서 찾기 쉬워서 워크스페이스를 분리했습니다...!

> 이렇게 고정값으로 박혀있는 id나중에 문제되지는 않겠죠?

- 이건... 무시하렵니다 /_ \ 이거까지 가면 글이 더이상 모노레포가 아니게 될까봐...ㄷㄷ 
아니면 내부에 useId를 static하게 수정하는 방안도 있을거 같습니다(react peerDeps를 18로 함)

`T` prefix는.. 사실 대출 1년 넘게 하면서 남아있는 버릇인데 vscode에서 검색이 쉬워서 계속 쓰게 되는거 같습니닷 ㅋㅋ; (옛날 사람되는 중..)

**Comment by yceffort** [comment]
넵넵! ㅋㅋㅋ 감사합니다.

추가로 vite.config.mts 외에도 빌드 파일도 .mjs 로 되어 있었는데 (타입은 .d.ts) (feature/33 브랜치 기준) 파일 확장자에서 다 통일감있게 m 을 제거하셔도 좋을거같아요!

**Comment by yujeongJeon** [comment]
.ts로 통일하였습니다! 혹시 더 리뷰 주실 사항은 따로 또 이슈 주시면 반영하겠습니다 :)!
